In [2]:
import pandas as pd
print(pd.__version__)
df=pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],columns=['A','B','C'],index=['X','Y','Z'])
df

3.0.0

   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [ ]:
import pandas as pd
import numpy as nb
coffefile=pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/warmup-data/coffee.csv")
print(coffefile)
coffefile.loc[0:3 , ["Day","Units Sold"]]
for index , row in coffefile.iterrows():
    print(index)
    print(row["Day"])
    print(row["Units Sold"])
    print("\n\n\n")
coffefile['price']=5
removed=coffefile.drop(columns=['price'])
removed.head()
removed['price for type']=nb.where(removed['Coffee Type']=='Espresso',8,10)
removed['revenu']=removed['price for type']*removed['Units Sold']
removed.head()

         Day Coffee Type  Units Sold  price for type  revenu
0     Monday    Espresso          25               8     200
1     Monday       Latte          15              10     150
2    Tuesday    Espresso          30               8     240
3    Tuesday       Latte          20              10     200
4  Wednesday    Espresso          35               8     280

In [ ]:
import pandas as pd
olympicrewrds=pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/results.csv")
olympicrewrds['hight category']=olympicrewrds['']

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
308403,2022.0,Winter,Luge,"Singles, Men (Olympic)",Marián Skupek,148983,SVK,NaN,26.0,False,NaN
308404,2022.0,Winter,Alpine Skiing (Skiing),"Slalom, Women (Olympic)",Elsa Fermbäck,148984,SWE,NaN,28.0,False,NaN
308405,2022.0,Winter,Alpine Skiing (Skiing),"Team, Mixed (Olympic)",Hilma Lövblom,148985,SWE,Sweden,13.0,False,NaN
308406,2022.0,Winter,Alpine Skiing (Skiing),"Giant Slalom, Women (Olympic)",Hilma Lövblom,148985,SWE,NaN,NaN,False,NaN
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",Charlotta Säfvenberg,148986,NaN,NaN,24.0,False,NaN

In [ ]:
# filtering data using the loc function
import pandas as pd
import string
sportsfile=pd.read_csv("https://raw.githubusercontent.com/KeithGalli/complete-pandas-tutorial/refs/heads/master/data/bios.csv")
print("this the search opperaton for hight criteria:\n")
hightsearch=sportsfile.loc[(sportsfile["height_cm"]>215)&(sportsfile["born_country"]=="MAR"),["name","height_cm","born_country"]].sort_values("height_cm",ascending=False)
print(hightsearch)
print("\n")
print("this the search opperaton for the name criteria:\n")
namesearch=sportsfile.loc[sportsfile["name"].str.contains("Moad",case=False,na=False),["name", "born_country"]]
print(namesearch)
sportsfile['hight category']=sportsfile['height_cm'].apply(lambda x: 'short' if x<165 else('avrage' if x<190 else(pd.NA if pd.isna(x) else 'tall')))
sportsfile.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,hight category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,avrage
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,avrage
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,avrage
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,NaN

In [3]:
df=pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/LXjSAttmoxJfEG6il1Bqfw/Product-sales.csv")
df.head()

,OrderID,Product,Category,Quantity,Price,Total,OrderDate,CustomerCity
0,1,Laptop,Electronics,2,800,1600,2022-01-10,New York
1,2,Smartphone,Electronics,3,600,1800,2022-02-15,Los Angeles
2,3,Desk Chair,Furniture,5,150,750,2022-03-12,Chicago
3,4,Notebook,Stationery,10,2,20,2022-04-05,Houston
4,5,Monitor,Electronics,1,300,300,2022-05-21,Miami